p = 8; 
np = 2*p*(p+1); 
sp = (p+1)^2; 
N = 3*np; 
J = [1:3:N 2:3:N 3:3:N];

% Randomly generated 
V = rand(N,1); V = V./norm(V); 
PV = VshProj(V,'VW'); 
P2V = VshProj(PV,'VW'); 
fprintf('\n ||(P-P^2)[V]|| = %1.2e ',norm(PV-P2V));  
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Generated by decaying spectrum
Vh = rand(sp,3); 
Vh = repmat((0.5.^(0:sp-1)'),1,3).*Vh; 
Vh(1,2:3)=0; 
Vh(p^2+1:end,:)=0; Vh = Vh(:); 
V2(J,:) = VshSyn(Vh,'VW'); 

Vh2 =VshAna(V2(J,:),'VW'); 
fprintf('\n ||Vh - Vh2|| = %1.2e ',norm(Vh-Vh2));
figure; 
plot(log10(abs(Vh2)),'o'); hold on; 
plot(log10(abs(Vh)),'.r');

PV2 = VshProj(V2,'VW'); 
fprintf('\n ||(P-I)[V2]|| = %1.2e ',norm(V2-PV2));
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Projection matrix
PM = make_vshprojection(p,1);
%PM(J,J) = PM; 

%Apply permutation matrix
PMV = PM*PV; 
PMV2 = PM*V2;  

%Check 
fprintf('\n ||(PM-P)[V]|| = %1.2e ',norm(PMV-PV));
fprintf('\n ||(PMV2-V2)[V2]|| = %1.2e \n',norm(PMV2-V2));

PMV2h = VshAna(PMV2(J,:),'VW'); 
figure; plot(log10(abs(PMV2h)),'o'); hold on; plot(log10(abs(Vh2)),'.r'); 