p = 8; 
np = 2*p*(p+1); 
sp = (p+1)^2; 
N = np; 

% Randomly generated 
V = rand(N,1); V = V./norm(V); 
PV = ShProj(V); 
P2V = ShProj(PV); 
fprintf('\n ||(P-P^2)[V]|| = %1.2e ',norm(PV-P2V));  
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Generated by decaying spectrum
Vh = rand(sp,1); 
Vh = (0.5.^(0:sp-1)').*Vh; 
Vh(p^2+1:end,:)=0; Vh = Vh(:); 
V2 = shSyn(Vh); 

Vh2 =shAna(V2); 
fprintf('\n ||Vh - Vh2|| = %1.2e ',norm(Vh-Vh2));
figure; 
plot(log10(abs(Vh2)),'o'); hold on; 
plot(log10(abs(Vh)),'.r');

PV2 = ShProj(V2); 
fprintf('\n ||(P-I)[V2]|| = %1.2e ',norm(V2-PV2));
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Projection matrix
PM = make_projection(p);
%PM(J,J) = PM; 

%Apply permutation matrix
PMV = PM*PV; 
PMV2 = PM*V2;  

%Check 
fprintf('\n ||(PM-P)[V]|| = %1.2e ',norm(PMV-PV));
fprintf('\n ||(PMV2-V2)[V2]|| = %1.2e \n',norm(PMV2-V2));

PMV2h = shAna(PMV2); 
figure; plot(log10(abs(PMV2h)),'o'); hold on; plot(log10(abs(Vh2)),'.r'); 