this_dir = fileparts(mfilename('fullpath'));
repo_root = fileparts(fileparts(fileparts(this_dir)));

addpath(genpath(fullfile(repo_root, 'spheroidal')));
addpath(genpath(fullfile(repo_root, 'support')));
addpath(genpath(fullfile(repo_root, 'FMMLIB')));
addpath(genpath(fullfile(repo_root, 'LCPsolvers')));
clear SSph_MatVec;

%% SETUP
n3 = 2;
p = 8;
kerd = 3;
out = true;
Nt = 15;
dt = 0.05;
denseMV = true;
tdisc = 'euler';
bench_backend = 'cartesian';

mdist = 1e-1;
collision_eps = 1e-1;

equ_radii = [0.6 0.6];
polar_radii = [1.0 1.0];
C = [...
    -0.58 0.0 -0.35; ...
     0.58 0.0  0.65; ...
];
shape_type = calculate_shape_type(equ_radii, polar_radii);

force_mag = 3.0;
F_const = [ force_mag, -force_mag; ...
            0.0,       0.0; ...
            0.0,       0.0 ];
Ffun = @(t, C, varargin) F_const;
Tfun = @(t, C, q) zeros(3, n3);


bodydist = struct( ...
    'algo','moving_balls', ...
    'max_iter', 200, ...
    'tol',1e-7 ...
);
parbd = struct( ...
    'n3',n3, ...
    'equ_radii',equ_radii, ...
    'polar_radii',polar_radii, ...
    'shape_type',shape_type, ...
    'p',p, ...
    'Ct',C, ...
    'mdist',mdist, ...
    'collision_eps',collision_eps, ...
    'out',out, ...
    'bodydist', bodydist, ...
    'tsl_backend', bench_backend ...
);

% Parameters for linear solvers
parslv = struct(...
    'solver','gmres', ...
    'tol',1e-4, ...
    'maxit',250, ...
    'rst',8, ...
    'precond_type','bkdiag', ...
    'prec',[], ...
    'colsolver','BBPGD', ...
    'coltol',1e-5, ...
    'colmaxit',200, ...
    'col_tolrel',1e-4, ...
    'col_tolabs',1e-5, ...
    'deflate',true, ...
    'td_sparse_nn', true, ...
    'td_sparse_nn_reg', 1e-10, ...
    'td_sparse_nn_inverse', 'lu', ...
    'td_sparse_nn_direct_max_bodies', 0, ...
    'td_sparse_nn_extract_max_bodies', 2, ...
    'td_sparse_nn_reuse_local_state', true, ...
    'td_sparse_nn_spai_reg', 1e-8, ...
    'td_sparse_nn_spai_drop_tol', 1e-10, ...
    'td_sparse_nn_compare_reference', true, ...
    'td_sparse_nn_compare_max_bodies', 2, ...
    'td_p_coarse', false, ...
    'td_low_rank', false, ...
    'td_two_level', false ...
);

Fparams = struct(...
    'parbd',parbd, ...
    'parslv',parslv, ...
    'Nt',Nt, ...
    'dt',dt, ...
    'comp',true, ...
    'type','FTfun', ...
    'denseMV',denseMV, ...
    'typeMV','SSph', ...
    'tdisc',tdisc, ...
    'Tfun',Tfun, ...
    'Ffun',Ffun, ...
    'plotFlag',true ...
);

% Plot parameters
Fparams.plotFlag = true;
Fparams.plotTrajectories = true;
Fparams.plotTrajMaxPoints = 350;
Fparams.plotSurfaceAlpha = 0.2;
Fparams.plotGrid = true;
Fparams.plotColor = 'mu';
Fparams.plotColorMode = 'inf';
Fparams.plotForceVectors = true;
Fparams.plotView = [15 18];
Fparams.plotTitle = 'Oblique collision';

init_file = getenv('SPH_INIT_FILE');
if isempty(init_file)
    init_arg = [];
else
    init_arg = init_file;
    fprintf('Resuming from checkpoint: %s\n', init_arg);
end

timestamp = datestr(now, 'yyyymmdd_HHMMSS');
output_name = sprintf('Oblique_collision_sparse_nn_%s_%s', parslv.td_sparse_nn_inverse, timestamp);

% Use a timestamped output name to avoid overwriting previous runs.
spheroidal_mobility(output_name, Fparams, init_arg);
