%{
Test of spheroids in free Stokes flow subjected to a cylindrical
solid-body rotational flow about the z-axis.
%}

addpath(genpath('../../../spheroidal'));
addpath(genpath('../../../support'));
addpath(genpath('../../../FMMLIB'));
addpath(genpath('../../../LCPsolvers'));
clear SSph_MatVec;

%% SETUP
scenario = '2body';

% Simulation parameters
out = true; % outside vs inside sphere
Nt = 200;
dt = 0.1;
denseMV = true; % Dense vs FMM off diagonal
tdisc = 'euler';
mdist = 1e-1;
collision_eps = 1e-1;

% u_{\infty}(x) = omega_z * (-y * e_x + x * e_y).
angular_rate = 1.0;
background_flow = struct( ...
    'enabled', true, ...
    'U0', [0 0 0], ...
    'A', [0 -angular_rate 0; angular_rate 0 0; 0 0 0] ...
);

% Spheroid parameters
p = 8; % Spharm degree p

switch scenario
    case '1body'
        n3 = 1;
        equ_radii = 1/2;
        polar_radii = 1;
        C = [2 0 0];
        oblate = false;
    case '2body'
        n3 = 2;
        equ_radii = [1/2 1/2];
        polar_radii = [1 1];
        C = [ ...
            2 0 1; ...
           -2 0 -1; ...
        ];
        oblate = false(n3, 1);
    otherwise
        error('Scenario not supported.');
end

% Linear solver parameters
tol = 1e-4;

% Force and torque functions
Tfun = @(t,C,q) zeros(3, n3);
Ffun = @(t,C,varargin) zeros(3, n3);

% Parameters for initial setup of bodies
bodydist = struct( ...
    'algo', 'moving_balls', ...
    'max_iter', 100, ...
    'tol', 1e-6 ...
);

parbd = struct( ...
    'n3', n3, ...
    'equ_radii', equ_radii, ...
    'polar_radii', polar_radii, ...
    'shape_type', oblate, ...
    'p', p, ...
    'Ct', C, ...
    'mdist', mdist, ...
    'collision_eps', collision_eps, ...
    'out', out, ...
    'bodydist', bodydist ...
);

% Parameters for linear solvers
parslv = struct( ...
    'solver', 'gmres', ...
    'tol', tol, ...
    'maxit', 200, ...
    'rst', 4, ...
    'precond_type', 'bkdiag', ...
    'prec', [], ...
    'colsolver', 'BBPGD', ...
    'coltol', 1e-4, ...
    'colmaxit', 100, ...
    'col_tolrel', tol, ...
    'col_tolabs', 0.1 * tol ...
);

Fparams = struct( ...
    'parbd', parbd, ...
    'parslv', parslv, ...
    'Nt', Nt, ...
    'dt', dt, ...
    'comp', true, ...
    'type', 'FTfun', ...
    'denseMV', denseMV, ...
    'typeMV', 'SSph', ...
    'tdisc', tdisc, ...
    'Tfun', Tfun, ...
    'Ffun', Ffun, ...
    'plotFlag', true, ...
    'background_flow', background_flow ...
);

% Plot parameters
Fparams.plotFlag = true;
Fparams.plotTrajectories = true;
Fparams.plotTrajMaxPoints = 200;
Fparams.plotSurfaceAlpha = 0.3;
Fparams.plotGrid = true;
Fparams.plotColor = 'sigma';
Fparams.plotColorMode = 'inf';
Fparams.plotForceVectors = false;
Fparams.plotView = [45 20];
Fparams.plotTitle = sprintf('Cylindrical rotational flow about z-axis (omega = %.2f)', angular_rate);

spheroidal_mobility('cylindrical_flow', Fparams, []);