restoredefaultpath;
this_dir = fileparts(mfilename('fullpath'));
repo_root = fileparts(fileparts(fileparts(this_dir)));
addpath(repo_root, '-begin');

addpath(genpath(fullfile(repo_root, 'spheroidal')), '-begin');
addpath(genpath(fullfile(repo_root, 'support')), '-begin');
addpath(genpath(fullfile(repo_root, 'FMMLIB')), '-begin');
addpath(genpath(fullfile(repo_root, 'LCPsolvers')), '-begin');

rbs_code_path = fullfile(repo_root, 'Phoretic_Particles', 'Code', 'RBS_Code');
if exist(rbs_code_path, 'dir') == 7
    rmpath(genpath(rbs_code_path));
end

%% SETUP
scenario = '2body';

% Simulation parameters
kerd = 1; % Kernel dimension
Nt = 400;
dt = 0.05;
denseMV = true; % Dense vs FMM off diagonal 
tdisc = 'euler';
mdist = 1e-2; % Collision parameter ?
collision_eps = 1e-2;

% Janus particle settings
lambda = 1;
gamma = 1;
boundary_label = @(X,y) (0.5*X*y'./sqrt(sum(X.^2,2)).^2 + 1/2);

% Spheroid parameters
p  = 8; % Spharm degree p

switch scenario
    case '1body'
        n3 = 1; % Number of objects
        equ_radii = [1/2];
        polar_radii = [1];
        C = [0 0 0]; % object centers
        oblate = false;
    case '2body'
        n3 = 2;
        equ_radii = [1/2 2/3];
        polar_radii = [1 1];
        C = [...
            0 0.7 0; ...
            0 -0.7 1; ...
        ];
        oblate = [false false];
    case '3bodystable'
        n3 = 3;
        equ_radii = [1/2 1/2 1/2];
        polar_radii = [1 1 1];
        % Equilateral triangle
        C = [...
            0 2*sqrt(3)/4 0; ...
            1 -2*sqrt(3)/4 0; ...
            -1 -2*sqrt(3)/4 0; ...
        ];
        oblate = [false false false];
    otherwise
        error('Scenario not supported.');
end

init_dir = -C;
init_norm = sqrt(sum(init_dir.^2,2));
zero_dir = init_norm < eps;
if any(zero_dir)
    init_dir(zero_dir,:) = repmat([0 0 1], sum(zero_dir), 1);
    init_norm = sqrt(sum(init_dir.^2,2));
end
init_dir = init_dir./repmat(init_norm,1,3);

% Linear solver parameters
tol = 1e-4;

% Parameters for collision algorithm
bodydist = struct( ...
    'algo','moving_balls', ...
    'max_iter', 100, ...
    'tol',1e-6 ...
);

% Parameters for initial setup of bodies
parbd = struct( ...
    'n3',n3, ...
    'equ_radii',equ_radii, ...
    'polar_radii',polar_radii, ...
    'shape_type',oblate, ...
    'p',p, ...
    'Ct',C, ...
    'mdist',mdist, ...
    'collision_eps',collision_eps, ...
    'bodydist',bodydist ...
);

% Parameters for linear solvers
parslv = struct(...
    'solver','gmres', ...
    'tol',tol, ...
    'maxit',200, ...
    'rst',4, ...
    'precond_type','bkdiag', ...
    'prec',[], ...
    'colsolver','BBPGD', ...
    'coltol',1e-4, ...
    'colmaxit',100, ...
    'col_tolrel',tol, ...
    'col_tolabs',0.1*tol ...
);

Fparams = struct(...
    'parbd',parbd, ...
    'parslv',parslv, ...
    'Nt',Nt, ...
    'dt',dt, ...
    'comp',true, ...
    'type','JanusAmp', ...
    'lambda', lambda, ...
    'gamma', gamma, ...
    'init_dir', init_dir, ...
    'boundary_label', boundary_label, ...
    'denseMV',denseMV, ...
    'typeMV','SSph', ...
    'tdisc',tdisc, ...
    'plotFlag',true ...
);

% Plot parameters
Fparams.plotFlag = true;
Fparams.plotTrajectories = true;
Fparams.plotTrajMaxPoints = 200;
Fparams.plotSurfaceAlpha = 0.3;
Fparams.plotGrid = true;
Fparams.plotColor = 'sigma';
Fparams.plotColorMode = 'l2';
Fparams.plotForceVectors = true;
Fparams.plotView = [115 30];

spheroidal_mobility('JanusAmp', Fparams, []);
