%{
Test of spheroids in free Stokes flow subjected to gravity.

One spheroid should not induce any rotation, but multiple spheroids might
(even if they don't collide) due to pressure disturbances.
%}

this_dir = fileparts(mfilename('fullpath'));
repo_root = fileparts(fileparts(fileparts(this_dir)));

addpath(genpath(fullfile(repo_root, 'spheroidal')));
addpath(genpath(fullfile(repo_root, 'support')));
addpath(genpath(fullfile(repo_root, 'FMMLIB')));
addpath(genpath(fullfile(repo_root, 'LCPsolvers')));
clear SSph_MatVec;

%% SETUP
scenario = '4body';

% Simulation parameters
kerd = 3; % Kernel dimension
out = true; % outside vs inside sphere
Nt = 40;
dt = 0.1;
denseMV = false; % Dense vs FMM off diagonal 
tdisc = 'euler';
mdist = 1e-1; % Collision parameter ?
collision_eps = 1e-1;

% Spheroid parameters
p  = 8; % Spharm degree p

switch scenario
    case '1body'
        n3 = 1; % Number of objects
        equ_radii = [1/2];
        polar_radii = [1];
        C = [0 0 0]; % object centers
        oblate = false;
    case '2body'
        n3 = 2;
        equ_radii = [1/2 1/2];
        polar_radii = [1 1];
        C = [...
            -1 0 0; ...
            1.5 0 0; ...
        ];
        oblate = [false false];
    case '4body'
        n3 = 4;
        equ_radii = [1/2 1/2 2/3 1/2];
        polar_radii = [1 1 1 1];
        C = [...
            -1.5 0 0;
            1.5 0 0;
            0 0.6 0.2;
            0 -0.6 0;  
        ];
        oblate = false(1, 4);
    otherwise
        error('Scenario not supported.');
end

% Linear solver parameters
tol = 1e-4;

% Force and torque functions (let gravity be proportional to volume)
body_shape_types = calculate_shape_type(equ_radii, polar_radii);
body_volumes = LOCAL_calculate_volume(n3, p, equ_radii, polar_radii, body_shape_types);
% Tfun = @(t,C,varargin) [20*(body_volumes).^3; zeros(2,n3) ];
% Ffun = @(t,C,q) zeros(3,n3);
Tfun = @(t,C,q) zeros(3,n3);
Ffun = @(t,C,varargin)  [zeros(2,n3) ; -1*(body_volumes).^3];

% Parameters for initial setup of bodies
bodydist = struct( ...
    'algo','moving_balls', ...
    'max_iter', 100, ...
    'tol',1e-6 ...
);
parbd = struct( ...
    'n3',n3, ...
    'equ_radii',equ_radii, ...
    'polar_radii',polar_radii, ...
    'shape_type',oblate, ...
    'p',p, ...
    'Ct',C, ...
    'mdist',mdist, ...
    'collision_eps',collision_eps, ...
    'out',out, ...
    'bodydist', bodydist, ...
    'slp_backend', 'cartesian', ...
    'tsl_backend', 'cartesian', ...
    'parallel_near', true ...
);

% Parameters for linear solvers
parslv = struct(...
    'solver','gmres', ...
    'tol',tol, ...
    'maxit',200, ...
    'rst',16, ...
    'precond_type','bkdiag', ...
    'prec',[], ...
    'td_sparse_nn', true, ...
    'td_sparse_nn_reg', 1e-10, ...
    'td_sparse_nn_inverse', 'lu', ...
    'td_sparse_nn_extract_max_bodies', 2, ...
    'td_sparse_nn_reuse_local_state', true, ...
    'colsolver','BBPGD', ... %% Collision parameters will need to be changed after update.
    'coltol',1e-4, ...
    'colmaxit',100, ...
    'col_tolrel',tol, ...
    'col_tolabs',0.1*tol ...
);

Fparams = struct(...
    'parbd',parbd, ...
    'parslv',parslv, ...
    'Nt',Nt, ...
    'dt',dt, ...
    'comp',true, ...
    'type','FTfun', ...
    'denseMV',denseMV, ...
    'typeMV','SSph', ...
    'tdisc',tdisc, ...
    'Tfun',Tfun, ...
    'Ffun',Ffun, ...
    'plotFlag',true ...
);

% Plot parameters
Fparams.plotFlag = true;
Fparams.plotTrajectories = true;
Fparams.plotTrajMaxPoints = 200;
Fparams.plotSurfaceAlpha = 0.2;
Fparams.plotGrid = true;
Fparams.plotColor = 'mu';
Fparams.plotColorMode = 'inf';
Fparams.plotForceVectors = true;
Fparams.plotView = [35 15];
Fparams.plotColorLimits = [0.5 1];


spheroidal_mobility('', Fparams, []);

%% Utility functions
function volumes = LOCAL_calculate_volume(ns, p, equ_radii, polar_radii, shape_types)
    volumes = zeros(1, ns);
    for i=1:ns
        shape_type = shape_types(i);
        switch shape_type
            case "sphere"
                volumes(i) = (4/3)*pi*equ_radii(i)^3;
            case "oblate"
                [u0_i, a_i] = calculate_u0_and_a_from_radii(shape_type, equ_radii(i), polar_radii(i));
                pts = oblate_spheroid_shape(p, u0_i, a_i);
                s = SurfaceSph(pts);
                volumes(i) = s.volume;
            case "prolate"
                [u0_i, a_i] = calculate_u0_and_a_from_radii(shape_type, equ_radii(i), polar_radii(i));
                pts = prolate_spheroid_shape(p, u0_i, a_i);
                s = SurfaceSph(pts);
                volumes(i) = s.volume;
            otherwise
                error('Unsupported shape type at index %d.', i);
        end
    end
end
