
addpath(genpath('../../../spheroidal'));
addpath(genpath('../../../support'));
addpath(genpath('../../../FMMLIB'));
clear SSph_MatVec;

%% SETUP
n3 = 2;
p = 8;
kerd = 3;
out = true;
Nt = 400;
dt = 0.05;
denseMV = true;
tdisc = 'euler';

mdist = 3;
collision_eps = 1e-2;

equ_radii = [0.6 0.6];
polar_radii = [1.0 1.0];
C = [...
    -0.55 0.0 -0.35; ...
     0.55 0.0  0.65; ...
];
shape_type = calculate_shape_type(equ_radii, polar_radii);

force_mag = 3.0;
F_const = [ force_mag, -force_mag; ...
            0.0,       0.0; ...
            0.0,       0.0 ];
Ffun = @(t, C, varargin) F_const;
Tfun = @(t, C, q) zeros(3, n3);


bodydist = struct( ...
    'algo','moving_balls', ...
    'max_iter', 200, ...
    'tol',1e-7 ...
);
parbd = struct( ...
    'n3',n3, ...
    'equ_radii',equ_radii, ...
    'polar_radii',polar_radii, ...
    'shape_type',shape_type, ...
    'p',p, ...
    'Ct',C, ...
    'mdist',mdist, ...
    'collision_eps',collision_eps, ...
    'out',out, ...
    'bodydist', bodydist ...
);

% Parameters for linear solvers
parslv = struct(...
    'solver','gmres', ...
    'tol',1e-4, ...
    'maxit',250, ...
    'rst',8, ...
    'precond_type','bkdiag', ...
    'prec',[], ...
    'colsolver','BBPGD', ...
    'coltol',1e-5, ...
    'colmaxit',200, ...
    'col_tolrel',1e-4, ...
    'col_tolabs',1e-5 ...
);

Fparams = struct(...
    'parbd',parbd, ...
    'parslv',parslv, ...
    'Nt',Nt, ...
    'dt',dt, ...
    'comp',true, ...
    'type','FTfun', ...
    'denseMV',denseMV, ...
    'typeMV','SSph', ...
    'tdisc',tdisc, ...
    'Tfun',Tfun, ...
    'Ffun',Ffun, ...
    'plotFlag',true ...
);

% Plot parameters
Fparams.plotFlag = true;
Fparams.plotTrajectories = true;
Fparams.plotTrajMaxPoints = 350;
Fparams.plotSurfaceAlpha = 0.2;
Fparams.plotGrid = true;
Fparams.plotColor = 'mu';
Fparams.plotColorMode = 'inf';
Fparams.plotForceVectors = true;
Fparams.plotView = [15 18];
Fparams.plotTitle = 'Oblique collision';

% Use a dedicated output name to avoid overwriting other tests.
spheroidal_mobility('Oblique collision', Fparams, []);
