%{
Test of spheroids in free Stokes flow subjected to gravity.

One spheroid should not induce any rotation, but multiple spheroids might
(even if they don't collide) due to pressure disturbances.
%}

addpath(genpath('../../../spheroidal'));
addpath(genpath('../../../support'));
addpath(genpath('../../../FMMLIB'));
addpath(genpath('../../../LCPsolvers'));
clear SSph_MatVec;

%% SETUP
scenario = '3bodypaper';

% Simulation parameters
kerd = 1; % Kernel dimension
out = true; % outside vs inside sphere
Nt = 400;
dt = 0.05;
denseMV = true; % Dense vs FMM off diagonal 
tdisc = 'euler';
mdist = 1e-2; % Collision parameter ?
collision_eps = 1e-2;

% MHD parameters
mur = 2; % mu / mu_0
H0 = [0 10 0];

% Spheroid parameters
p  = 12; % Spharm degree p

switch scenario
    case '1body'
        n3 = 1; % Number of objects
        equ_radii = [1/2];
        polar_radii = [1];
        C = [0 0 0]; % object centers
        oblate = false;
    case '2bodyattract'
        n3 = 2;
        equ_radii = [1/2 2/3];
        polar_radii = [1 1];
        C = [...
            0 0.7 0; ...
            0 -0.7 0; ...
        ];
        oblate = [false false];
    case '2bodyrepel'
        n3 = 2;
        equ_radii = [1/2 2/3];
        polar_radii = [1 1];
        C = [...
            1 0 0; ...
            -1 0 0; ...
        ];
        oblate = [false false];
    case '3bodystable'
        n3 = 3;
        equ_radii = [1/2 1/2 1/2];
        polar_radii = [1 1 1];
        % Equilateral triangle
        C = [...
            0 2*sqrt(3)/4 0; ...
            1 -2*sqrt(3)/4 0; ...
            -1 -2*sqrt(3)/4 0; ...
        ];
        oblate = [false false false];
    case '3bodypaper'
        n3 = 3;
        equ_radii = [1/2 1/2 1/2];
        polar_radii = [1 1 1];
        % Equilateral triangle
        C = [...
            0 0 0; ...
            0 3 0; ...
            1.5 1.5 0; ...
        ];
        oblate = [false false false];
    otherwise
        error('Scenario not supported.');
end

% Linear solver parameters
tol = 1e-4;

% Parameters for collision algorithm
bodydist = struct( ...
    'algo','moving_balls', ...
    'max_iter', 100, ...
    'tol',1e-6 ...
);

% Parameters for initial setup of bodies
parbd = struct( ...
    'n3',n3, ...
    'equ_radii',equ_radii, ...
    'polar_radii',polar_radii, ...
    'shape_type',oblate, ...
    'p',p, ...
    'Ct',C, ...
    'mdist',mdist, ...
    'collision_eps',collision_eps, ...
    'out',out, ...
    'bodydist',bodydist ...
);

% Parameters for linear solvers
parslv = struct(...
    'solver','gmres', ...
    'tol',tol, ...
    'maxit',200, ...
    'rst',4, ...
    'prtype','bkdiag', ...
    'prec',[], ...
    'colsolver','BBPGD', ... %% Collision parameters will need to be changed after update.
    'coltol',1e-4, ...
    'colmaxit',100, ...
    'col_tolrel',tol, ...
    'col_tolabs',0.1*tol ...
);

Fparams = struct(...
    'parbd',parbd, ...
    'parslv',parslv, ...
    'Nt',Nt, ...
    'dt',dt, ...
    'comp',true, ...
    'type','MHD', ...
    'denseMV',denseMV, ...
    'typeMV','SSph', ...
    'tdisc',tdisc, ...
    'mur',mur, ...
    'H0',H0, ...
    'plotFlag',true ...
);

% Plot parameters
Fparams.plotFlag = true;
Fparams.plotTrajectories = true;
Fparams.plotTrajMaxPoints = 200;
Fparams.plotSurfaceAlpha = 0.3;
Fparams.plotGrid = true;
Fparams.plotColor = 'sigma';
Fparams.plotColorMode = 'l2';
Fparams.plotForceVectors = true;
Fparams.plotView = [115 30];

spheroidal_mobility('', Fparams, []);
