%{
Test of spheroids in free Stokes flow subjected to gravity.
%}

%% SETUP
% Simulation parameters
kerd = 3; % Kernel dimension
dense = true; % Dense vs FMM off diagonal 
out = true; % outside vs inside sphere

% Spheroid parameters
p  = 16; % Spharm degree p 
n3 = 1; % Number of objects
u0 = 2/sqrt(3);
a = 1./u0;
C = [0 0 0]; % object centers
oblate = false;

% Linear solver parameters
tol = 1e-4; mdist = 1e-3;

% Force and torque functions (gravity is proportional to volume)
body_volumes = LOCAL_calculate_volume(n3, p, u0, a, oblate);
Tfun = @(t,C) zeros(3,n3);
Ffun = @(t,C) [zeros(2,n3) ; -9.81*(body_volumes.').^3];

parbd = struct( ...
    'Shape','spheroid', ...
    'n3',n3, ...
    'u0',u0, ...
    'a',a, ...
    'shape_type',oblate, ...
    'p',p, ...
    'Ct',C, ...
    'mdist',mdist, ...
    'eps',ep, ...
    'mdist',mdist, ...
    'out',out ...
);

parslv = struct(...
    'solver','gmres', ...
    'tol',tol, ...
    'maxit',200, ...
    'rst',4, ...
    'prtype','bkdiag', ...
    'prec',[], ...
    'colsolver','BBPGD', ... %% Collision parameters will need to be changed after update.
    'coltol',1e-4, ...
    'colmaxit',100, ...
    'col_tolrel',tol, ...
    'col_tolabs',0.1*tol ...
);

Fparams = struct(...
    'parbd',parbd, ...
    'parslv',parslv, ...
    'Nt',Nt, ...
    'dt',dt, ...
    'comp',true, ...
    'type','FTfun', ...
    'denseMV',denseMV, ...
    'typeMV','Vsh', ...
    'tdisc',tdisc, ...
    'Tfun',Tfun, ...
    'Ffun',Ffun ...
);

spheroidal_mobility(fname, Fparams, []);

%% Utility function
function volumes = LOCAL_calculate_volume(ns, p, u0, a, oblate)
    volumes = zeros(1, ns);
    for i=1:ns
        if oblate(i)
            pts = oblate_spheroid_shape(p, u0, a);
        else
            pts = prolate_spheroid_shape(p, u0, a);
        end
        s = SurfaceSph(pts);
        volumes(i) = s.volume;
    end
end