function [SpTg,SpTr,SpY] = Surfgrad_coeffs(p,pm,R,vin,vout,test)
%{
This code computes the spherical harmonic coefficient matrices (sparse)
needed to evaluate the traction of S[mu] or D[mu] for the Stokes layer
potentials using vector spherical harmonics. 

Inputs 

p  - (int) - spherical harmonic degree used to compute (p > pm) 
pm - (int) - degree to which SpTg, SpTr and SpY are computed
R  - (double) - Radii (usually 1) 
vin - (string) type of vector spherical harmonics input 
vout - (string) type of vector spherical harmonics output 
test - (bool) perform tests to check coefficients (default is false) 

Outputs
SpTg - (sparse 3*spm x 3spm) Tangent part of the operator
SpTr - (sparse 3*spm x 3spm) Radial part of the operator
SpY  - (sparse 3*spm x 3spm) Pressure dot N (scalar spharm)

%}

addpath ../
if nargin<6
test=false;
end

if test
   vout='VW'; 
   % Eigenvalues
    SVeg  = @(n) n./((2*n+1).*(2*n+3)); 
    SWeg  = @(n) (n+1)./((2*n+1).*(2*n-1));
    SXeg  = @(n) 1./(2*n+1); 

    % Exterior Formulas
    % Vnm
    SVext = @(r,n) SVeg(n).*r.^(-n-2); 
    SpVext = @(r,n) (-n-2).*SVeg(n).*r.^(-n-3);
    % Wnm
    SWVext = @(r,n) (n./(4*n+2)).*(r.^(-n-2)-r.^(-n));
    SWWext = @(r,n) SWeg(n).*r.^(-n);
    SpWVext = @(r,n) (n./(4*n+2)).*((-n-2).*r.^(-n-3)-(-n).*r.^(-n-1));
    SpWWext = @(r,n) (-n).*SWeg(n).*r.^(-n-1);
    % Pressure generated by S[Wn]
    PWext = @(r,n) -n.*r.^(-n-1); 
    % Xnm
    SXext = @(r,n) SXeg(n).*r.^(-n-1);
    SpXext = @(r,n) -(n+1).*SXeg(n).*r.^(-n-2);
end

if nargin<5 
   if nargin==3
    vin='VW'; 
   end
   
   vout=vin;
end

np = 2*p*(p+1); npm = 2*pm*(pm+1); 
sp=(p+1)^2; spm=(pm+1)^2;
ii = (1:sp)'; 
nn = floor(sqrt(ii-1)); 
mm=ii-nn.^2-nn-1;

% Sphere params and unit vectors
[u,v] = gl_grid(p);
Sc = SurfaceSph(shape_gallery(p,''));
er = [sin(u).*cos(v) sin(u).*sin(v) cos(u)];
ev = repmat(sin(u),1,3).*[-sin(v) cos(v) zeros(np,1)];
eu = repmat(sin(u),1,3).*[cos(u).*cos(v) cos(u).*sin(v) -sin(u)];

% Initialize
Shu = zeros(3*sp,3*spm,3); Shv=Shu; Shr=Shu; 
ShTg =zeros(3*spm,3*spm,3);
ShTr =zeros(3*spm,3*spm,3);
ShY = ShTg; 

if strcmp(vin,'VW')
    V1 = 'Vnm'; V2 = 'Wnm'; V3 = 'Xnm';  
elseif strcmp(type,'GX')
    V1 = 'YNr'; V2 = 'GY'; V3 = 'Xnm';
end

for i=1:spm
    
n=nn(i); m=mm(i); 

Vn = Vnm(V1,Sc,n,m,u,v,er);
[TrVn,TgVn] = LOCAL_Find_stress_comps(Vn,u,eu,ev,er,Sc); 

tmp = VshAna(TgVn,vout);
idx = [(1:spm) (1:spm)+sp (1:spm)+2*sp]; 
ShTg(:,i,:) = tmp(idx,:); 

tmp = VshAna(TrVn,vout);
idx = [(1:spm) (1:spm)+sp (1:spm)+2*sp]; 
ShTr(:,i,:) = tmp(idx,:);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Test 
if test
SVn = SVext(R,n)*Vn; 
dKVn = SpVext(R,n)*Vn; 

[DVu,DVtu] = LOCAL_Find_stress(SVn,dKVn,u,Sc,er,R,eu);
[DVv,DVtv] = LOCAL_Find_stress(SVn,dKVn,u,Sc,er,R,ev);
[DVr,DVtr] = LOCAL_Find_stress(SVn,dKVn,u,Sc,er,R,er);

fprintf('\n Error (DV + DV^T) (eu,ev,er) \n')
norm(DVu + DVtu - (SVext(R,n)/R)*TgVn(:,1) - SpVext(R,n)*TrVn(:,1))
norm(DVv + DVtv - (SVext(R,n)/R)*TgVn(:,2) - SpVext(R,n)*TrVn(:,2))
norm(DVr + DVtr - (SVext(R,n)/R)*TgVn(:,3) - SpVext(R,n)*TrVn(:,3)) 

Shu(:,i,1) = VshAna(DVu+DVtu,vout);
Shv(:,i,1) = VshAna(DVv+DVtv,vout);
Shr(:,i,1) = VshAna(DVr+DVtr,vout);
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Wn = Vnm(V2,Sc,n,m,u,v,er); 
Y = Ynm(n,m,u,v); 

if strcmp(V2,'GY')
   Wn = reshape(reshape(Wn,[],3).',[],1);  
end

[TrWn,TgWn] = LOCAL_Find_stress_comps(Wn,u,eu,ev,er,Sc); 

tmp = VshAna(TgWn,vout);
idx = [(1:spm) (1:spm)+sp (1:spm)+2*sp]; 
ShTg(:,i+spm,:) = tmp(idx,:);

tmp = VshAna(TrWn,vout);
idx = [(1:spm) (1:spm)+sp (1:spm)+2*sp]; 
ShTr(:,i+spm,:) = tmp(idx,:);

YI = repmat(Y,1,3); 
Yu = reshape((YI.*eu),[],1); Yv = reshape((YI.*ev),[],1);
Yr = reshape((YI.*er),[],1); 

tmp = VshAna([Yu Yv Yr],vout); 
idx = [(1:spm) (1:spm)+sp (1:spm)+2*sp]; 
ShY(:,i+spm,:) = tmp(idx,:);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Test
if test
SWn = SWWext(R,n)*Wn + SWVext(R,n)*Vn; 
dKWn = SpWWext(R,n)*Wn + SpWVext(R,n)*Vn;
PWn = PWext(R,n)*Y;

[DWu,DWtu] = LOCAL_Find_stress(SWn,dKWn,u,Sc,er,R,eu);
[DWv,DWtv] = LOCAL_Find_stress(SWn,dKWn,u,Sc,er,R,ev);
[DWr,DWtr] = LOCAL_Find_stress(SWn,dKWn,u,Sc,er,R,er);

fprintf('\n Error (DW + DW^T) (eu,ev,er) \n')
norm(DWu + DWtu - (SWWext(R,n)/R)*TgWn(:,1) - SpWWext(R,n)*TrWn(:,1) - (SWVext(R,n)/R)*TgVn(:,1) - SpWVext(R,n)*TrVn(:,1))
norm(DWv + DWtv - (SWWext(R,n)/R)*TgWn(:,2) - SpWWext(R,n)*TrWn(:,2) - (SWVext(R,n)/R)*TgVn(:,2) - SpWVext(R,n)*TrVn(:,2))
norm(DWr + DWtr - (SWWext(R,n)/R)*TgWn(:,3) - SpWWext(R,n)*TrWn(:,3) - (SWVext(R,n)/R)*TgVn(:,3) - SpWVext(R,n)*TrVn(:,3))

PWnI = repmat(PWn,1,3); 
PWnu = reshape((PWnI.*eu),[],1); PWnv = reshape((PWnI.*ev),[],1); 
PWnr = reshape((PWnI.*er),[],1); 

Shu(:,i,2) = VshAna(DWu+DWtu-PWnu,vout);
Shv(:,i,2) = VshAna(DWv+DWtv-PWnv,vout);
Shr(:,i,2) = VshAna(DWr+DWtr-PWnr,vout);
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Xn = Vnm(V3,Sc,n,m,u,v,[]); 

[TrXn,TgXn] = LOCAL_Find_stress_comps(Xn,u,eu,ev,er,Sc); 

tmp = VshAna(TgXn,vout);
idx = [(1:spm) (1:spm)+sp (1:spm)+2*sp]; 
ShTg(:,i+2*spm,:) = tmp(idx,:);

tmp = VshAna(TrXn,vout);
idx = [(1:spm) (1:spm)+sp (1:spm)+2*sp]; 
ShTr(:,i+2*spm,:) = tmp(idx,:);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Test
if test
SXn = SXext(R,n)*Xn; 
dKXn = SpXext(R,n)*Xn;

[DXu,DXtu] = LOCAL_Find_stress(SXn,dKXn,u,Sc,er,R,eu);
[DXv,DXtv] = LOCAL_Find_stress(SXn,dKXn,u,Sc,er,R,ev);
[DXr,DXtr] = LOCAL_Find_stress(SXn,dKXn,u,Sc,er,R,er);

fprintf('\n Error (DX + DX^T) (eu,ev,er) \n')
norm(DXu + DXtu - (SXext(R,n)/R)*TgXn(:,1) - SpXext(R,n)*TrXn(:,1))
norm(DXv + DXtv - (SXext(R,n)/R)*TgXn(:,2) - SpXext(R,n)*TrXn(:,2))
norm(DXr + DXtr - (SXext(R,n)/R)*TgXn(:,3) - SpXext(R,n)*TrXn(:,3))

Shu(:,i,3) = VshAna(DXu+DXtu,vout);
Shv(:,i,3) = VshAna(DXv+DXtv,vout);
Shr(:,i,3) = VshAna(DXr+DXtr,vout);
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

end

if test   
    
% Test for random density 
ii = (1:spm)'; 
nn = floor(sqrt(ii-1)); 
pmx=pm-1; 
qVh = [rand(pmx^2,1); zeros((pm+1)^2-pmx^2,1)];
qWh = [rand(pmx^2,1); zeros((pm+1)^2-pmx^2,1)];
qXh = [rand(pmx^2,1); zeros((pm+1)^2-pmx^2,1)];
zp = zeros(spm,1);
nk=7;
qVh = zp; qWh = zp; qXh=zp; qWh(nk)=1; 
% extend qh to account for S[W] = cWW*W + cWV*V
qhex = [qVh;qWh;qWh;qXh]; 

%bz = rand(3,1);  
bz = [0 0 1].'; 

% Compute Tq using Vsh coeffs in ShTg, ShTr and ShY
idx = [1:spm ; 1:spm ; (spm+1):2*spm ; (2*spm+1):3*spm]; idx=idx'; 
Tgqhz = zeros(size(ShTg,1),4); Trqhz = Tgqhz; 

Sext = (1/R)*[SVext(R,nn) ; SWVext(R,nn) ; SWWext(R,nn) ; SXext(R,nn)]; 
Spext = [SpVext(R,nn) ; SpWVext(R,nn) ; SpWWext(R,nn) ; SpXext(R,nn)];

qhg = Sext.*qhex; qhr = Spext.*qhex;
qWp = PWext(R,nn).*qWh;  

display(qhg(abs(qhg)>1e-6).')
display(qhr(abs(qhr)>1e-6).')
display(qWp(abs(qWp)>1e-6).')

for i=1:4         
idq = (1:spm) + (i-1)*spm;
Tgqhz(:,i) = [ShTg(:,idx(:,i),1)*qhg(idq,:) ShTg(:,idx(:,i),2)*qhg(idq,:) ShTg(:,idx(:,i),3)*qhg(idq,:)]*bz; 
Trqhz(:,i) = [ShTr(:,idx(:,i),1)*qhr(idq,:) ShTr(:,idx(:,i),2)*qhr(idq,:) ShTr(:,idx(:,i),3)*qhr(idq,:)]*bz; 
end
Pqhz = [ShY(:,(spm+1):2*spm,1)*qWp  ShY(:,(spm+1):2*spm,2)*qWp  ShY(:,(spm+1):2*spm,3)*qWp]*bz;

ShTq = sum(Tgqhz + Trqhz,2) + Pqhz; 
Tq = LOCAL_VshSyn(ShTq,vout); 
Tq =  reshape(reshape(Tq,3,[]).',[],1);  

figure; plot(real(Tq),'b')

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Compute Tq2 using (Du + Du' - pI)z
sqh = [SVext(R,nn) ; SWVext(R,nn) ; SWWext(R,nn) ; SXext(R,nn)].*qhex; 
sqh = [sqh(1:spm,:)+sqh(spm+1:2*spm,:);sqh(2*spm+1:end,:)]; 
Sq = LOCAL_VshSyn(sqh,vout);  

dsqh = [SpVext(R,nn) ; SpWVext(R,nn) ; SpWWext(R,nn) ; SpXext(R,nn)].*qhex; 
dsqh = [dsqh(1:spm,:)+dsqh(spm+1:2*spm,:);dsqh(2*spm+1:end,:)]; 
Spq = LOCAL_VshSyn(dsqh,vout);  

Pzh = Pqhz;
Pz = LOCAL_VshSyn(Pzh,vout); 
Pz =  reshape(reshape(Pz,3,[]).',[],1); 

[u,v] = gl_grid(pm);
Sc = SurfaceSph(shape_gallery(pm,''));
er = [sin(u).*cos(v) sin(u).*sin(v) cos(u)];
ev = repmat(sin(u),1,3).*[-sin(v) cos(v) zeros(npm,1)];
eu = repmat(sin(u),1,3).*[cos(u).*cos(v) cos(u).*sin(v) -sin(u)];

z = bz(1)*eu + bz(2)*ev + bz(3)*er; 
[Dq,Dqt] = LOCAL_Find_stress(Sq,Spq,u,Sc,er,R,z); 
Tq2 = Dq+Dqt+Pz; 
ShTq2 = VshAna(Tq2,vout);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Compare

figure; 
Dqh = VshAna(Dq,vout); Dqth = VshAna(Dqt,vout); 
plot(abs(Dqh),'ob'); hold on; 
plot(abs(Dqth),'or');
plot(abs(VshAna(Pz,vout)),'og');

figure; 
norm(Tq-Tq2)
plot(abs(ShTq),'ob')
hold on; 
plot(abs(ShTq2),'.r')

figure; 
plot(abs(ShTq-ShTq2),'ok')

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Experiment w/ Laplace S'
np=npm; 
dotp = @(x,y) x(1:np,:).*conj(y(1:np,:)) +...
    x(np+1:2*np,:).*conj(y(np+1:2*np,:)) + x(2*np+1:3*np,:).*conj(y(2*np+1:3*np,:));
z = bz(1)*eu+bz(2)*ev+bz(3)*er; 
n=3; m=-2; 
Y = Ynm(n,m,u,v); 
Seg  = @(n) (1./(2*n+1)); 
SYext = @(r,n) Seg(n).*r.^(-n-1); 
SpYext = @(r,n) -Seg(n).*(n+1).*r.^(-n-2);
SY = SYext(R,n)*Y; 
dSY = SpYext(R,n)*Y; 
GS = Sc.geoProp.Grad(SY); GS = (1/R)*reshape(GS.to_array,[],3);
Gu = repmat(dSY,1,3).*er + GS; 

Guz = dotp(Gu(:),z(:));

GY = Vnm('GY',Sc,n,m,u,v,er); 
Guz2 = SpYext(R,n)*dotp(er(:),z(:)).*Y + (SYext(R,n)/R)*dotp(GY(:),z(:));
 
figure; plot(abs(Guz-Guz2))
norm(Guz-Guz2)

end

%Store ShTr, ShTg and ShY as sparse arrays
[jj,ii] = meshgrid(1:3*spm,1:3*spm); 
SpTr = cell(3,1); SpTg  = SpTr; SpY = SpTr; 

for j=1:3
    idTr = find(abs(ShTr(:,:,j))>1e-12); 
    idTg = find(abs(ShTg(:,:,j))>1e-12); 
    idY = find(abs(ShY(:,:,j))>1e-12); 
    
    tmp = ShTr(:,:,j); SpTr{j} = sparse(ii(idTr),jj(idTr),tmp(idTr),3*spm,3*spm); 
    tmp = ShTg(:,:,j); SpTg{j} = sparse(ii(idTg),jj(idTg),tmp(idTg),3*spm,3*spm);
    tmp = ShY(:,:,j);   SpY{j} = sparse(ii(idY),jj(idY),tmp(idY),3*spm,3*spm);
end

end

function [Dun,Dutn] = LOCAL_Find_stress(S,dS,u,Sc,Nr,Rtrg,z)

Mv = @(M1,M2,M3,v) [sum(M1.'.*v.').' ; sum(M2.'.*v.').'; sum(M3.'.*v.').'];

s1 = S(1:3:end); s2=S(2:3:end); s3 = S(3:3:end); 
%Rtrg = reshape(Rtrg,3,[])'; 

Dgs1 = Sc.geoProp.Grad(s1); Dgs1 = (1./(Rtrg+(Rtrg==0))).*reshape(Dgs1.to_array,[],3);
Dgs2 = Sc.geoProp.Grad(s2); Dgs2 = (1./(Rtrg+(Rtrg==0))).*reshape(Dgs2.to_array,[],3);
Dgs3 = Sc.geoProp.Grad(s3); Dgs3 = (1./(Rtrg+(Rtrg==0))).*reshape(Dgs3.to_array,[],3);

Gs1 = repmat(dS(1:3:end),1,3).*Nr + Dgs1; 
Gs2 = repmat(dS(2:3:end),1,3).*Nr + Dgs2; 
Gs3 = repmat(dS(3:3:end),1,3).*Nr + Dgs3; 

%Dun(1:3:end) = sum(Gs1'.*z')'; Dun(2:3:end) = sum(Gs2'.*z')'; Dun(3:3:end) = sum(Gs3'.*z')'; 
Dun = Mv(Gs1,Gs2,Gs3,z); 

Gutx = [Gs1(:,1) Gs2(:,1) Gs3(:,1)]; 
Guty = [Gs1(:,2) Gs2(:,2) Gs3(:,2)];
Gutz = [Gs1(:,3) Gs2(:,3) Gs3(:,3)]; 

%Dutn(1:3:end) = sum(Gutx'.*z')'; Dutn(2:3:end) = sum(Guty'.*z')'; Dutn(3:3:end) = sum(Gutz'.*z')'; 
Dutn = Mv(Gutx,Guty,Gutz,z); 

end

function [Tr,Tgrad] = LOCAL_Find_stress_comps(f,u,eu,ev,er,Sc)

Mv = @(M1,M2,M3,v) [sum(M1.'.*v.').' ; sum(M2.'.*v.').'; sum(M3.'.*v.').'];

f1 = f(1:3:end); f2=f(2:3:end); f3 = f(3:3:end); 

Dgf1 = Sc.geoProp.Grad(f1); Dgf1 = reshape(Dgf1.to_array,[],3);
Dgf2 = Sc.geoProp.Grad(f2); Dgf2 = reshape(Dgf2.to_array,[],3);
Dgf3 = Sc.geoProp.Grad(f3); Dgf3 = reshape(Dgf3.to_array,[],3);

Gr1 = repmat(f1,1,3).*er;
Gr2 = repmat(f2,1,3).*er; 
Gr3 = repmat(f3,1,3).*er; 

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Gutx = [Dgf1(:,1) Dgf2(:,1) Dgf3(:,1)]; 
Guty = [Dgf1(:,2) Dgf2(:,2) Dgf3(:,2)];
Gutz = [Dgf1(:,3) Dgf2(:,3) Dgf3(:,3)]; 

Grtx = [Gr1(:,1) Gr2(:,1) Gr3(:,1)]; 
Grty = [Gr1(:,2) Gr2(:,2) Gr3(:,2)];
Grtz = [Gr1(:,3) Gr2(:,3) Gr3(:,3)]; 

%Du + Dut  
Tgrad(:,1) = Mv(Dgf1,Dgf2,Dgf3,eu)  + Mv(Gutx,Guty,Gutz,eu);
Tgrad(:,2) = Mv(Dgf1,Dgf2,Dgf3,ev)  + Mv(Gutx,Guty,Gutz,ev);
Tgrad(:,3) = Mv(Dgf1,Dgf2,Dgf3,er)  + Mv(Gutx,Guty,Gutz,er);

Tr(:,1) = Mv(Gr1,Gr2,Gr3,eu)  + Mv(Grtx,Grty,Grtz,eu);
Tr(:,2) = Mv(Gr1,Gr2,Gr3,ev)  + Mv(Grtx,Grty,Grtz,ev);
Tr(:,3) = Mv(Gr1,Gr2,Gr3,er)  + Mv(Grtx,Grty,Grtz,er); 

end

function F = LOCAL_VshSyn(Vsh,type)

[d1,d2] = size(Vsh);
sp = d1/3; 
p = sqrt(sp)-1;
np = 2*p*(p+1); 
[u,v] = gl_grid(p);
Sc = SurfaceSph(shape_gallery(p,''));
Nr = [sin(u).*cos(v) sin(u).*sin(v) cos(u)];
F = zeros(3*np,1); 

if strcmp(type,'VW')
   V1 = 'Vnm'; V2 = 'Wnm'; V3 = 'Xnm';  
elseif strcmp(type,'GX')
   V1 = 'YNr'; V2 = 'GY'; V3 = 'Xnm';  
end

for k=0:p
   ind = k^2+1:(k+1)^2; 
   Vk = Vnm(V1,Sc,k,[],u,v,Nr); 
   Wk = Vnm(V2,Sc,k,[],u,v,Nr); 
   Xk = Vnm(V3,Sc,k,[],u,v,Nr); 
   
   F = F + [Vk Wk Xk]*Vsh([ind' ; ind'+sp ; ind'+2*sp]); 
end

end