function S = shape_gallery(p, shapeIn, cnts) 
% S = shape_gallery(p,shapeIn) - returns the point samples form the desired shape.
% S = shape_gallery(p,shapeIn,cnts) - replicates the shape with centers in
% cnts
%
% Given the number of discretization points (p), and the desired shape, it
% returns the sample points on a Gauss-uniform grid. For instance a grid
% generated by GL_GRID. The output is an array with [x;y;z] coordinates
%
% SEE ALSO: GL_GRID.
%

  shape = '';
  if(nargin>1), shape = shapeIn;end

  [u, v] = gl_grid(p);
  np = length(u);
  spherical = false;
  ax = 1; ay = 1; az = 1;

  switch shapeIn
   case 'ellipseZ'
    rho = 1;
    ax = 1/2; ay = 1/2;
    spherical = true;
   
   case 'ellipseZ2'
   rho = 1;
   ax = 1/4; ay = 1/4;
   spherical = true;

   case 'ellipseZ3'
   rho = 1;
   ax = 1/3; ay = 1/3;
   spherical = true;

   case 'ellipseX'
    rho = 1;
    ay = .5;
    az = .5;
    % ay=3/5;
    % az=3/5;
    spherical = true;
    
   case 'oblateZ'
    rho = 1;
    % az = 1/3; 
    az = 2/sqrt(7);
    spherical = true; 

   case 'dumbbell'
    rho = 1 + real(Ynm(2,0,u,v));
    spherical = true;
    
   case 'tilt_dumbbell'	
    rho = 1 + real(Ynm(2,1,u,v)) + .1*real(Ynm(3,2,u,v));
    spherical = true;
    
   case 'butternut'
    %rho = .1+abs(Ynm(1,0,u,v)).^2;
    if(isstruct(shape) && isfield(shape,'cf'))
      cf = shape.cf;
    else
      cf = .8;
    end
    z = cos(u);
    s = 1-cf*cos(pi*(z-.2)/2); 
    %constriction factor, tweak the coefficient of
    %the cos to get a slimmer/wider neck.
    r = sqrt((1-z.^2).*s.^2);
    [x, y] = pol2cart(v,r);
    S = [x;y;z];
    
   case 'tri_ap'  % ~ triangle antiprism
    rho = 1 + .2*exp(-3*real(Ynm(3,2,u,v)));
    spherical = true;
    
   case 'square_ap' % ~ square antiprism
    rho = exp(.5*sin(u).^4.*cos(u).*cos(4*v));
    spherical = true;
    
   case 'oblate85'
    rho = 1;
    % ax = .47;
    az = .47; % change of minor axis from x to z.
    spherical = true;
    
   case 'oblate75'
    rho = 1;
    % ax = .366;
    az = .366;
    spherical = true;

   case 'oblate65'
    rho = 1;
    % ax = .29;
    az = .29;
    spherical = true;
    
    case 'Y43'
    n = 4; m = 3; r=0.5;                      
    rho = 1 + r*real(Ynm(n,m,u,v));      
    spherical = true;   
    
   case 'Y87'
    n = 8; m = 7; r=0.5; 
    rho = 1 + r*real(Ynm(n,m,u,v));      
    spherical = true;
    
    case 'Y1615'
    n = 16; m = 15; r=0.5;   
    rho = 1 + r*real(Ynm(n,m,u,v));      
    spherical = true; 
    
   case 'RY43'  
    n = 4; m = 3; 
    r = rand();                      
    rho = 1 + r*real(Ynm(n,m,u,v));      
    spherical = true;   
    
   case 'RY87'
    n = 8; m = 7;
    r = rand();
    rho = 1 + r*real(Ynm(n,m,u,v));      
    spherical = true;
    
    case 'RY1615'
    n = 16; m = 15;
    r = rand();  
    rho = 1 + r*real(Ynm(n,m,u,v));      
    spherical = true;      
    
   otherwise
    rho = 1;
    spherical = true;
  end
  
  if(spherical)
      x = ax*rho.*sin(u).*cos(v);
      y = ay*rho.*sin(u).*sin(v);
      z = az*rho.*cos(u);
      S = [x;y;z];
  end

 if(nargin>2 && ~isempty(cnts))
   cnts = reshape(cnts,[],3);
   ns   = size(cnts,1);   
   S    = repmat(S,1,ns);
   for ii=1:ns
     C = repmat(cnts(ii,:),np,1);
     S(:,ii) = S(:,ii) + C(:);
   end     
 end
