% Oblate SL spectrum tests
% reference: SLtest.m by L Crowder, DLtest_oblate by T Li
clear;
pstart=3; pend=16; 
parr=pstart:pend; spend=(pend+1)^2;
uu=2/sqrt(3);
a = 1./sqrt(1+uu.^2);
% a = 1./uu;
f = @(u,v) exp(sin(u).^4.*cos(u).*cos(4*v));

pars=SpheroidalParameters;
pars.u0 = uu;
pars.a = a;
pars.oblate=1;

% check surfaces generated by SurfSph vs SpheroidParam.
%{
pars.plot()
hold on;
Sns = SurfaceSph(shape_gallery(8,'oblateZ')); 
Xns = reshape(Sns.cart.to_array,[],3);
scatter3(Xns(:,1),Xns(:,2),Xns(:,3));
hold off
axis equal
legend("oblate spheroid","SurfaceSphere")
%}

%% on surface
% %{
errnorm = zeros(length(parr),1);
for l=1:length(parr)
    p=parr(l);
    [u,v]=gl_grid(p);
    % Y = Ynm(3,-1,u,v); 
    % fac=1./sqrt(uu^2+cos(u).^2); Y = Y.*fac;
    Y = f(u,v); % target density is arbitrary periodic function.
    pars.sigma= Y;
    myDY=spheroidalSL(pars);
    [DYsh,DY]=SDY(p,'SL',1,Y);
    errnorm(l) = norm(abs(myDY - DY));
end
figure;
semilogy(parr,errnorm);
title("SL[f] function value error oblate");
% %}

%% off surface
% %{
dists = [2;2.5;4.5];
uu_trg=uu/2; a_trg=1/sqrt(1+uu_trg^2);
% a_trg=1/uu_trg;
[up,vp] = gl_grid(pend);
Yp = f(up,vp);

pot='SL_L_3D';
KEparams = Kernel_Eval_parameters(pot,0,1,1,1,1e-8,2,400,1);
KEparams.dim = 3;
Xself=oblate_spheroid_shape(pend,uu,a);
Sns = SurfaceSph(Xself);
KEparams.X = Xself;
[~, gwt]=g_grid(pend+1);
wt = pi/pend*repmat(gwt', 2*pend, 1)./sin(gl_grid(pend));
wt = wt(:);
Wns = Sns.geoProp.W; Wns= Wns.*wt;
KEparams.W2 = Wns.';

Xtrg=oblate_spheroid_shape(pend,uu_trg,a_trg);

errs_kernel = zeros(length(dists), length(parr));

for d=1:length(dists)
    Xtrg_dist=Xtrg+dists(d).*ones(size(Xtrg));
    SLmat = Kernel_Eval(Xtrg_dist,Xself,KEparams);
    calcSY = SLmat * Yp;
    
    for l=1:length(parr)
        p = parr(l);
        [u,v] = gl_grid(p);
        Y = f(u,v);
        pars.sigma=Y;
        SLY = spheroidalSL(pars,Xtrg_dist);
        errs_kernel(d,l) = norm(abs(SLY-calcSY));
    end
end

figure;
for d=1:length(dists)
    semilogy(parr,errs_kernel(d,:)); hold on;
end
hold off;
xlabel("p"); ylabel("norm error");
title("difference from Kernel Eval, oblate")

% %}


